name: spdx
description: Verify that files include SPDX license headers

branding:
  icon: zap
  color: gray-dark

inputs:
  licenses:
    description: >
      A space-separated list of all accepted licenses. For example:

      Apache-2.0 MIT
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.licenses }}" | xargs $GITHUB_ACTION_PATH/verify-spdx-headers
      shell: bash
