name: spdx
description: Verify that files include SPDX license headers

branding:
  icon: zap
  color: gray-dark

inputs:
  licenses:
    description: >
      Extensions and acceptable SPDX headers for them.
      Provide a dictionary, with file types as the keys and a list of accepted
      licenses as the values. For example:

      {
        "rs": ["Apache-2.0", "MIT"],
        "py": ["GPLv3"]
      }
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/verify-spdx-headers "${{ inputs.extensions }}"
      shell: bash
